#+DATE: <2019-07-08 周一>
#+STARTUP: SHOWALL
#+TAGS: ou

* 关于晓敏的回忆

** Overview
    随着这段时间过去, 我也与 OU 的感情彻底告一段落了, 这段时间将近持续了一年时间左右,
    从去年四月份的某一天开始, 直到年初的初五的那天下午

** 印象深刻的回忆
    - 那天早上
    - 网吧的那天晚上
    - 去中央大街的那天
    - 那天晚上给她买吃的
    - 我们一起去看剧
    - 一起去吃广东菜那天
    - 我们一起去看晚会(科学会堂)
    - 那天我们出去一起拍照(毕业)
    - 在合肥的日子
    - 在上海的日子

 #+DATE: <2019-08-17 Sat>
** 站在我的角度的看法
*** 对于爱情
    晓敏是一个什么性格的人, 可能我个人的看法是片面的, 但即使这样, 我还是要谈谈我的想法的, 无论这种想法是否片面, 她对于我来说都是一个无比重要的人, 这一点永远也无法磨灭, 是她让我在认知中对别人有了一个更深入的理解.
    之所以她对于我来说无比重要, 是因为跟她在一起是我与这么多女生相处以来, 可以说是第一个真正相处过的人. 其中包含了一种真正的意义, 一种真正的感觉
    站在我个人的角度去看, 她只是一个普通的女孩, 一个我曾经喜欢过, 爱过的普通女孩. 但也正因为如此, 事情就失去了它原本的意义. 
    不知道怎么回事我心中有时候总有一个梦魇, 总觉得爱情应当与生活捆绑在一起, 而我对生活的渴望也会反映在对爱情的看法上, 这种想法尤其体现在工作比较繁忙的时候, 而这时候对爱情的渴求也自然变少了许多, 虽然这时一种看似实际的想法, 但这种爱情还称的上是真正的爱情吗, 或者说这种期待本身就是不切实际吧
    她是一个好女孩，不知道为什么我就喜欢不上来, 可能是我已经习惯孤单了, 也可能是曾经受到的伤害也让我变得小心翼翼, 但我却不知道这样是好还是坏.
    这段感情结束了, 我想或许这并不是一件坏的事情, 至少现在回忆起来, 它仍然是一件美好的体验
*** 对于人
*** (我)对她的偏颇看法[fn:1]
    这也就意味着她在未来不会发光, 但我明白她可能永远都意识不到这一点, 或者说， 在这个时代世界上大多数人可能都是如此, 这是因为
    她的内心是趋同的, 是拼命去寻找别人认同的, 而没有什么自身的特点,表面上想要变得更优秀, 但却并没有什么实
    际的行动, 在一开始, 我的第一印象是她拿着一本关于唐玄宗的书, 但我发现她在读书的过程中, 从未试图去深入理
    解这本书中要表达的内容, 我这才发现, 她所想要的不是去看书, 而是让别人都知道她在干什么, 
    突然想到 xyice 似乎也是一个这样的人， 只不过她更聪明一点罢了.
    而在平时的相处中, 也并没有体现出一种尊重的心, 殊不知, 在爱情中, 平等尊重才
    是最为重要的, 她的很多想法都是流露在外的, 与其说是无法控制感情, 更不如说是她对每一件事情都不是特别地
    在乎, 总觉得每件事情都是她的玩物, 每件事情都在她的手中, 她不懂得尊重, 也不懂得保护生活的美好, 那些喜
    欢在社交平台上评论的人, 表面上是喜欢与别人分享, 实际上却只是寻求自身的存在感, 不得不说, 在如今这个"信
    息发达"的社会, 人们越来越要求自己的存在感. 她的那些言语让我总觉得她像一个外人, 或者说, 是觉得她把我当
    成一个外人, 你要知道, 对待一件事物, 总是以自己的态度为主, 而不主动去考虑对方的心态, 这样只会让你与那
    个人越来越远
    她是一个想要去追求优越事物的人, 却从来没想主动把自己的生活变得"优越"
    当一个人不了解事情其中真正蕴含的意义, 一切都只是嘴上说说而已

* Footnotes

[fn:1] (曾经的看法， 我现在已经知道这么看人是不对的，故放在这里作为对我的警示)
