#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-05-23 Wed>
#+TITLE: 新阶段的第十九天 --- 对情感失望的开始 --- 如何避免随机因素控制我們的人生 --- 真正认识理性
#+TAGS: diary, communication
#+LAYOUT: post
#+CATEGORIES: 



总结: 成功的经验, 如何抑制情感的产生(远离情感产生的来源, 给予心灵适时的滋润)

不要太羡慕别人的情感, 因为情感的维持绝对不是依靠情感本身

先下几个结论:

1. 感情绝对不是靠得住的, 无论这种情感在产生时有多么浓烈
原因: 情感在时间的流转中会慢慢变淡, 同时也总会有别的其他的情感一同涌入把它冲淡

2. 理性是可以靠得住的, 但理性在某些情况下会有缺陷
原因: 1) 理性在当有强烈的情感冲击下, 不堪一击
      2) 理性是循序渐进的, 因此并不总是正确的

         
问题: 

首要问题:
1. 如何保持正确的理性
既然不能依赖於情感, 而情感在某些情况下会取代理性, 所以接下来的问题就是

2. 如何不进入情感主导的领域(如何避免产生强烈的情感)
由於情感是一种先天存在的属性, 这种属性并不能通过某种特殊的办法而消除掉, 所以只能通过外界行为加以抑制

3. 举出具体容易被情感主导的情景, 这种主导指的是情感拥有者本人内心的变化
   
   
方法问题:
1. 能否进行持续的思考?
这种思考需要两个先天必要的条件, 一是容易进行思考的客观主体, 二是要有一个能够持续思考的环境, 即不能够被其他事情干扰或打断
后续问题: 长时间一个人的独立思考是否会令思考者感受到孤独(后续: 什么是孤独, 孤独是唯心的吗?), 

2. 为什么要构造一个持续思考的环境

3. 什么是一个能够持续思考的环境, 而什么又不是呢?
一个简单的思维跳跃   

4.
后续问题: 容易产生思维跳跃的因素, 分为内在和外在
内在: 功利心
外在: 其他人的影响, 人际交往等
后续问题: 什么是功利心, 功利心表现在什么情况(举出具体例子)
后续问题: 如何避免功利心(具体列出什么行为是功利心的表现, 在某些情况或环境时要有一个什么样的具体动作)
行为1: 在我码字的時候就会想去知道自己写了多少字, 以此获得成就感
缺陷: 这种成就感会大幅减少继续工作下去的东西, 它本身就是一种麻醉剂
行为2: 在无目的的学习时不断想看表
缺陷: 此时的想法是想要草草了事, 而不是真正钻心於内容
行为3: 任何信仰的产生(对信仰的举例, 此问题可以单独列出一篇文章, 并区分信仰与喜爱, 喜爱绝不等同于信仰)
缺陷: 信仰会给人以宽慰感, 让人逃避思考
后续问题: 举手投足间对思考的打断(分类, 使用笔记本时, 与人交往时, 等等)
行为1: 在想起更新系统时就去更新, 而之后一直在看进度条(使用笔记本时)
行为2: 在突然想起某一个自己感兴趣的话题, 而此话题却是非专业性质的(使用笔记本时)
后续问题: 如何最小化思维跳跃时产生的影响(计划??)
后续问题: 为什么不能唯任务论, 1. 一个人真正的思考是源于心的(唯心), 而绝对不是简单的完成任务, 因为当人沦为了完成任务的机器时也就失去了作为人的意义.
                             2. 唯任务论是需要一种感情的注入的
后续问题: 为什么不能有功利心
后续问题: 感情的优点, 与利用这种优点时的弊端
正面的感情会
后续问题: 避免感性因素控制的最好方法
列出具体行为并进行避免, 把这些具体行为进行分级
后续问题: 如何进行反思, 什么时间进行反思
后续问题: 疲倦的陷阱是什么
大脑一片空白(在之前的文章里有所论述)
后续问题: 引起疲倦的陷阱的因素是什么
(没有持续思考?? 其他小的陷阱的引发??)

后续问题: 如何避免掉入疲倦的陷阱

后续问题: 有哪些情感会思考对象的变化(世俗)
情感1: 消费
自己拥有的东西(想要拥有更好的)
自己还未拥有的(想要去拥有)
情感2: 娱乐

被动方法: 方法的矫正
一种理性的高傲, 有时候可以避免掉入陷阱, 而保持专注
问题1: 这种理性的高傲是什么(这种高傲是一种什么心态)
这是一种绝不随意的态度, 轻视别人, 重视自己的内心, 而内心一定要有所想(这是一种思维的结果, 而不是思维的过程)
问题2: 如何保持这种高傲
既然想要高傲, 就一定要有一种保持高傲的条件, 但这种高傲决不能有一种优越感, 因为这是已经与之前理性的观念相违背的
这种高傲是一种不与人同流合污的

人们总会被某些"吸引人的"名词所迷惑, 殊不知它的背后只有一片虚无.

当时间过去后, 所有的情感, 惊喜, 震撼, 悲伤, 甚至於愛, 都会消失得无影无踪, 留下的只有其话语本身的意义, 在那时你才能真正明白什么是客观.



爱的理解: 
当你去理解愛情时, 会发现你当初看重的因素实际上却无足轻重, 所谓样貌什么的在一段时间过后都变成了"同一种面孔", 不会再令你有任何的激动, 而她的手也再不会有第一次那么柔软和动人, 这个時候真正珍贵的是她的和蔼的性格与愛你的始终不变的心, 这才是真正不变的.
