#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-06-05 Tue>
#+TITLE: 欲望永远不能被满足, 只能被抑制.
#+TAGS: diary, communication
#+LAYOUT: post
#+CATEGORIES: 

我大概只会喜欢两种人,
我在意第一种人是因为我在意的是别人看我们俩的眼光, 所以这种人必须有着出色的能力.
而我在意第二种人是因为我毫不在意别人对我们俩的看法, 即使别人对她冷眼相看我也毫不在乎.
因为我的眼睛已经看向了我的心裡.
你可能认为后一种才是真正的愛, 因为这种愛已经脱离的世俗的观念.
但对个人来讲, 前一种愛却可能给人以更大的动力.
也正是因为对别人看法的在意, 觉得必须与这种人在一起也必须有一种出色的能力,
对自己也就有了一种压力, 而这种压力是长期存在的(由於没有经历过所以无法验证)


论快感
快感是一种对短时间直接刺激神经单元, 引发兴奋的一种状态, 在这种状态是人是十分愉悦的. 快感是一种对事物本身的冲动, 但却不是一种对外在事物的动力.
例如: 喝酒, 吸烟, 性交, 吸毒, 赌博, 打游戏, 玩手机等都属於快感的行列, 这些行为都有一类特点, 就是成瘾性强, 不易戒去, 虽然在实施时十分兴奋, 但在事后人却十分疲惫, 这也是因为人的精力的固定的这种条件. 不同种类的产生快感的方式不同, 成瘾的程度也有所区分, 但有一定规律的是, 在一定时间内给人带来的快感越强, 这种行为的成瘾性越强, 危害也就越大. 
这种成瘾性的产生也是利用了人自身的弱点, 想要戒除成瘾性, 则需要人有着强大的毅力, 其中最困难的是, 由於人的神经元具有记忆性, 这些能带来快感的行为在人的大脑里留下印记, 这种印记对於你神经的印象是正面的, 所以你的神经本身也就把它当成了一种'好'印象, 所以它会不时地提醒你应该做这件事, 但这种基于人的原始的方式却会对人自身的适应行为带来极大的破坏, 包括人的身体, 思想方式等等, 唯一的一种戒除方式就是利用神经元的遗忘特性, 在长时间之后, 让神经元忘记这种快感, 从而达到戒除的目的. 而不是一次性把这种快感满足, 想当然地把这种快感'消灭'了.
欲望永远不能被满足, 只能被抑制.
但是除此之外, 还有一种更加棘手的事情需要解决, 对於吸毒来讲, 就是如何防止'复吸', 有些人在长时间的戒除后, 以为自己已经脱离了这种'成瘾性', 从而也就放松了警惕, 在这个处境下人是十分危险的, 如果第二次重新拾起了这种行为, 神经元会以极快的速度恢复对之前的记忆, 这也就相当於一种对知识的复习, 如果出现了这种行为, 下一次的戒除就将更加的辛苦, 更加地困难.
最好的戒除办法就是在接触这种行为之前就有一个清楚的认识, 从而对这种行为敬而远之. 但由於在接触之前或第一次接触时对这种行为毫不在意, 意味自己完全不会被这种行为所控制, 但转念想想, 又有哪种成瘾的行为, 在成瘾之前有'瘾‘呢, 但等到了解了这个事物的本质, 却已为时晚矣.
以上只是简单的分析了关于快感的一种状态.

---------------------------

只有清除了脑子中的想法, 把思想放空, 让自己变得’无知‘, 人才有继续做下去的动力.

---------------------------

~ 7:50-8:15
读<zen and motocycle>, 感觉非常不错

---------------------------

我在想, 如果当外星人来到地球, 他第一个惊讶的一定是为什么每个人手里都会拿一个四四方方的东西, 由於他们不知道, 一定会以为人类对自己的安全感很弱, 不然也没必要拿一个会发光的武器到处喊话 
# 人人自危,. 况且人又这么多, 环境又这么乱.

---------------------------

听说小敏要送给我礼物, 不由自主地又回想起小学的同桌在毕业之前送我的那盒纸星星. 那可能是我这一生第一次有人这么用心地送给我礼物, 而且也有可能永远再也不会有人更加用心, 那盒纸星星我已经找不到了, 可能是中学搬家的時候随便放在那个地方了, 现在想起来, 心裡总有些空落落的, 想当初在将要毕业的那些日子里, 当我还坐在她的旁边的時候, 当我呆呆地为她数着她一个一个叠得那些纸星星, 总觉得自己好像失去了最重要的东西. 她当时还叠得十分仔细, 看看是否叠得够了数, 总是这个颜色叠十个, 那个颜色叠二十, 直到现在我还记得她亲自告诉过我那盒星星是一定要叠多少个的, 而那个数字有着一个特定的含义. 当时我还不懂, 不懂为什么要叠到一个数字才好, 直到现在我才知道, 可能那些数字代表了一个特定的含义, 而那个含义也就是那个女生想要告诉我的一个东西.  

生活的很多的经历过去了, 而经历中的失败与挫折也过去了, 而现在那个数字, 也同那盒星星一样, 再也不属於我了.

我到还记清楚地记得她的名字, 叫方雪. 方是天园地方的方, 雪是洁白如雪的雪.
