#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-05-12 Sat>
#+TITLE: 新阶段的第九天 --- 很可能是另外一个阶段的开始
#+TAGS: diary, communication
#+LAYOUT: post
#+CATEGORIES: 

~ 9:30
一份平等且自由的愛是让人舒服的.

昨天是一个安逸的日子, 好久心里都没有这么平静了, 这份真正的爱情是不需要你去索求的, 时间久了, 自然会过来找你. 可能是这两天复杂的感情让我有些累了吧, 一份互相都不强求的愛才能保持新鲜. 当你还未经历过这种事情的時候, 总是觉得应该爱得神圣, 总觉得在爱情这方面应当如自己所愿, 但你是否想过愛情本身是一件什么东西, 有人认为愛是性是婚姻是清晨六点的吻是一堆孩子，也许真是这样的. 不过我觉得, 愛是两个人在一起互相体谅和宽慰, 是两个人待在一起而充满安静, 那种剥离了生活中应对他人时表现出来的虚伪, 互相之间只有一种纯粹, 好像待在一起就是一种对对方最好的报答. 
你真正去爱的人也是处於你的社会交往的范畴之内的, 但这种交往绝对与其他关系是不相等同的, 而是一种真正的情谊, 其中不掺杂任何虚伪的东西, 在对方面前, 你可以表现出最真实的自己, 而对方并不会去介意, 因为这就是愛情, 愛情就是一种坦白, 

愛情就是一种接受

真正的愛情是, 当我晚上梦见了你, 而自己则不会感到狂喜, 而是早上醒来时, 你的身影隐隐约约地印刻在自己的脑海里, 感觉那是一片淡淡的云彩, 飘浮在脑海上的天空, 忽隐忽现. 她不会占据你的全部思维, 因为那是一种轻松的感觉.

本来, 人是社会的动物, 不能要求人不受环境, 不受阶级舆论, 不受社会成见的影响而单凭自己的感情用事, 这就产生了很多的悲剧. 有的人因为屈服於社会舆论而遗憾终生, 有的人因为反抗社会舆论而遭到不幸. 茨威格在这里让我们看到, 外界的影响如何激起主人公心里汹涌的波涛, 内心的潮起潮落如何左右主人公感情的起伏, 行动的进退, 心灵的危机如何最终铸成这对青年男女的悲剧命运. --茨威格


只有当你给了对方自认为最珍贵的东西, 对方才会舍不得去分享.

~ 19:10
你体验过被你喜欢的人表白是什么感觉吗

生命的无趣 && 生活的压力 && 活着的目标 && 

表面上心里想得是不被影响, 而实际上所有你接触的事情都会或多或少地影响你对生活的理解和判断. 
你所直观的事物永远不会因为你的判断而消失, 而是会以另一种形式来映射进你的生命.
