#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-05-15 Tue>
#+TITLE: 到底改变了吗
#+TAGS: diary, communication
#+LAYOUT: post
#+CATEGORIES:

听着歌曲, 看着你的照片, 我就是想告诉你, 你发的每一张照片我都存下了, 我记得我们俩在一起的所有瞬间, 你知道我喜欢你什么吗? 我喜欢你的笑容, 和你的声音
曾经我以为我已经变得勇敢了, 但是前两天, 我在一个地方见到了和你好像好像的女孩, 那个女孩给了我一种感觉, 那种感觉和当年见到你是多么一样, 我也就好像变回了当年的自己, 我在那儿呆呆的望着你, 一句话也不敢多说, 生怕打乱了你的心弦, 那时我才发现, 我还是那么胆小, 面对自己喜欢的东西还是不敢去争取, 不过在远处望着你已经让我心满意足了, 和你在一起是我远远不敢奢求的.
曾经的我想要说服自己去忘记你, 但是没有一次成功. 现在我才知道, 对你的认识已经同我的生活历程连在了一起, 而一个人又怎能忘记自己的生活呢
我还清晰地在大一的時候你主动给了发的第一条信息, 我还记得我当时的感觉, 我欣喜若狂, 不住地兴奋, 我这辈子可能从未有过那么兴奋吧, 那种想喊出来, 但又发现整个世界都无法理解你的喜悦

我相信在这个世界, 只要有理性, 有一个合理的规划, 就一定能完成所有事情, 更何况对於如此脆弱的人性, 可能大部分人认为, 在喜欢这件事情上, 只要有缘分就足够让两个人在一起了, 可是我偏偏就觉得, 这个世界上最大的缘分就是遇见, 除了遇见, 剩下的所有事情都要自己去争取, 而不是被动的等待, 我是一个传统的人, 我觉得正是这种传统, 让我对这个世界的理解更加透彻, 传统的人更会去寻找出路, 虽然我不想对这个世界上我爱的人用这种方法, 但为了得到你我别无选择, 我会使用所有我能想到的方法接近你, 让你感受到我的存在. 我不知道你对我是否还有感觉, 所以我要用我所能想到的最周全的方式.

站在路边, 看着自己现在的状态, 我知道我不能再这样下去了, 我已经失去的东西已经够多了, 我不能够再失去你了.
我会从人性的弱点和心理方面, 我相信, 只要是人, 就一定有他的弱点, 就一定有其所想. 可能在这个路途上会受到伤害, 但我从未想过去惧怕, 因为失去你才是我最大的痛苦

我不知道这是不是又是一种感性的想法, 但我已经无所谓了, 我一定要这么做, 因为我已经无路可退

song: 好久不见, 平凡之路

拿出一个本子专门去记录
