#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-05-04 Fri>
#+TITLE: 感觉又是一个新的阶段
#+TAGS: diary, communication
#+LAYOUT: post
#+CATEGORIES: 

# 指出方法n ,场景n, n x m对应, 越详细，越能被真正理解


今天对人与人的相处与又有了一些不一样的看法， 而這种看法本身又含有一種愈加不确定的因素。 不同的人, 不同的事要应当有一種什么固定的态度, 都是要值得仔细探讨的.

在(同性)朋友身边不能唯唯诺诺, 磨磨叽叽. 

而在女生身边却应该有一種耐心. 一種聆听(当你了解与你相处的女生真正想法时，即只是一種想跟你安安静静地相处时，稍微偏诗意的句子比强硬的充满技巧的道理可能要有用一些). 


两个人相处在批判的時候应该尽量夸大這個人， 时刻注意常常提及這个人，让他感觉到自己的存在感， 這同时也会加强這个人对你的关注度(這个过程应当自然，而非刻意), 

但在群体之中却应该用一種肯定与否定交加，而不应该有疑问的成分在裡面， 就像这件事本身就自然而然地就会发生, 当然這種强硬的语态是很难被别人接受的， 这时候就要用上很多技巧了(這裡的技巧在所有交谈中都通用， 除了在安慰女生时或与女生交谈的其他场景时), 這種技巧包括在阐述结论时，要阐述在结论下的必要条件，这件事有什么/重要/後果(一定要让别人在你的話語中有抓手, 這样他才能真正重视你的話), 
在其他人提出无理或带有贬低的話語時必须沉默， 然后在适当的时间之后应当转移到别的話题上， 以及让别人真正正视他的错误
怎么能让其他人保持沉默，就是去压制或消除他表达的欲望，当他想要去表达的時候， 让他自己觉得他想表达的這件事无足轻重, 而让他自觉地沉默下来. 所以说想让别人沉默下来，自己不能始终保持沉默， 而是有选择，有技巧地去压制那个人想表达的欲望(例如在寝室, 想要真正安静地一个人呆一會儿，就要让别人认为你处于一个普通的状态， 没什么值得打扰的，因為人总是喜欢接触自己还未接触的东西， 或者说接触一个能引起新奇的东西， 而让自己变得普通，就可以避免這種情况的发生，所以你必须先接触他，在最短的时间内知道你想要表达的东西，之前描述的方法就正好能满足這裡的要求)

越是与个人相处，情感越应该细腻, 越应该关注那个人的内心世界(在不同性别，与不同阶级层次之间也要有不同方法, 女<异>性尤甚)
越是与群体相处，情感越应该表现得强硬, 越不应该犹犹豫豫， 越应该直接了当, 越应该有明确的方法与鲜明的套路

讨论什么時候应该带有笑容， 這是一個大的问题(难道真得应该想笑就笑吗??如果你能够仔细观察别人，就知道這样是欠妥的)
由于我們处於现代社会裡， 网络社交也成了沟通的一種不可避免的途径， 所以也应該探討如何更好地进行网络社交(用不用考虑在现实生活中的個人身份)

基准: 
  1. 吐字清晰
  2. 在方法一中: 語气不要僵硬(一種不列出事实就妄做评论的态度), 野蛮不讲理的态度

采用方法: 先带入具体场景, 再根据具体场景下选择对应的話题

# 备用: 先问对方一个问题, 然后根据他的回答评价或者继续追问
# 好处: 可以真正针对问题进行深入讨论, 不仅能够让这个人自己感到受关注, 而且这样做的话语连续性很强, 可以一直用这个话题说下去而不会冷场, 而且可以切换到"正直的态度"
# 场景: 一定要在真正有问题的時候进行提问, 不能没有问题现找问题, 在群体中不好使用(此处可以举例), 而在面对一个人则很好用

方法一(一種积极的, 寻求交流的态度): 
  話题: 对应人物自身的話题, 例如這個人有什么好的或者不好的地方(总之一定是不一样的地方)需要指出来的時候 
  神态动作: 眼睛尽量不要漂移, 說話時要把音量抬起来
  語气方式: 這種态度的强大之处在于对方必须跟着你的方向走, 而由于对方又不了解你问话的目的, 问话的对象又在他自己本身(這種話题意志不强大的人最容易接受, 因為人总是希望受到关注的)
  
  話题: 对应自己所遇见人物或事物的話题, 同上
  神态动作: 同上, 但可以放轻松些
  語气方式: 同上
  
方法二(一種正直的态度):  # 相对于寻求交流的方法, 這種方法更显得一個人有涵养, 而且还不会冒犯别人, 但相当于寻求交流的方法, 却无法拉近人与人的距离, 显得比较疏远
  話题: 對於工作, 学习, 学术问题
  神态动作: 眼睛尽量不要漂移, 眼神要坚定(这点很重要, 要让别人觉得你在认真对待這件事情), 面部表情要配合眼神要认真, 嘴角可以合起 
  語气方式: 語气要平稳坚定, 由於问题与态度的因素, 一定要字字清晰, 停顿也要多一些
  
方法三():



场景:

# 备用: 对於必须尊敬的人(老师, 学长, 父母亲人, 领导等)

1. 群体: 
   基准, 方法一

今天先不討論关于男女之间由于性的因素,产生的相互吸引的因素, 我只想说這種男女之间的情感如果不能跨過性這個问题，是很难谈到真正的友谊的， 這種问题我觉得在女性身上尤其明显， 对异性非愛即恨的态度要遠遠大于男性， 我觉得這種态度的产生要归结於母性本身，因為在自然界中， 利于自身繁衍的行为都会被层层筛选而被保留下来, 而這種行为或情感对於雌性的影响要遠大于雄性(当然每一个物種都各有差异, 但总体上這種现象还是普遍存在的)

16:07
写到了方法三: 今天实在是有些疲倦, 明天接着弄這個, 放到与(别人相处)的内容裡


从前慢

记得早先少年时
大家诚诚恳恳
说一句 是一句

清早上火车站
长街黑暗无行人
卖豆浆的小店冒着热气

从前的日色变得慢
车，马，邮件都慢
一生只够爱一个人

从前的锁也好看
钥匙精美有样子
你锁了 人家就懂了
# 美得无可复制， 而且美得让你不想复制， 不想去破坏



# 贾鹏伟的生日, 买菜, 写报告， 上课，牛萌拉了我三次手
