#+AUTHOR: vincent
#+EMAIL: xiaojiehao123@gmail.com
#+DATE: <2018-04-24 Tue>
#+TITLE: 关于肚财的孤独与菜铺的无助
#+TAGS:  film
#+LAYOUT: post
#+CATEGORIES: 

沉默的释迦, 孤独的肚财, 无助的菜铺

  我了解到这部片子, 是因为偶然间在网上看到这部片子击败了众多大陆优秀影片而独得金马奖, 这其中不妨有去年打破国内影史票房记录的<<战狼2>>, 能同时得到这么多人的肯定, 我觉得它一定是有其独到之处, 所以才看了这部片子. 而看完后这部影片也的确给我带来了很多思考. +在现如今国内电影市场如此景气, 而国内电影质量却与这种电影市场不相吻合时, 才更使人留意优秀的华语影片. 而我个人出于某些偶然因素, 又对这种小人物题材的影片又有种特别的喜爱, 所以才看了这部电影.+
  
  这部电影与别的作品不同的是, 看完这部作品, 你是能真切感受到电影的作者想要表达的东西的, 中间有一种能够被触摸的真实感, 虽然作品中的台词和独白都出奇得少, 甚至於释迦从始至终都没有说过一句话, 但这种少, 绝对不代表思维的零碎, 也反而正是这种内容上的少, 才更加能让观众专注於电影想要去表达的事物, 理解作者的思想.

  这部电影的名字--大佛普拉斯本身, 颇有些黑色幽默的趣味, 而在影片中导演也无时无刻不在利用他的这种黑色幽默, 来让观众真正理解这部电影的内涵, 之所以叫做“大佛普拉斯”, 是因为导演黄信尧的上一部电影就叫做"大佛", 而普拉斯则是英文plus的意思, 这一方面可以理解为电影大佛的续集, 另一方面也可以理解为对大佛本身, 或者是说通过这种宗教信仰体现导演本身对于生活的进一步+另类+理解与思考.

  这部长达一百分钟的影片, 实际上就是两个普通人肚财和菜铺的故事. 而他们的故事则也是平凡得不能再平凡, 普通得不能再普通的了. 很难想象在他们的生活中会发生什么不一般的事情. 但也正是由於在这种小人物身上的苦痛与艰辛, 才能引起大多数人的同感. 这种平凡也正是这种影片本身的闪光点, 我们所有人的生活也也都是这样普普通通, 平平淡淡, 那些在所谓的精彩只是别人评说出来的. 在哪里生活都一样, 没什么生活在别处.
  
  肚财是一个捡拾废品为生的人, 他身边没有亲人, 生活基本了无牵挂. 除了每天工作, 肚财唯一的乐趣就是抓娃娃, 在电影尾部当肚财死后菜铺第一次进入肚财的家里时, 看到一屋子肚财捡回来的废品和娃娃时, 那种孤独感压得人踹不上气来.

  像肚财这种底层人士, 按理说应该是数不胜数的. 不过又恰恰在这种辛酸的生活中, 能够反映出一种最真实的不幸. 为生活奔波, 为明天发愁, 为求人办事而低三下四, 这是每个人都会遇到的事. 这看似是一种磨难, 但其实并不是, 相反, 这才是生活本身, 生活中的边边角角, 反而, 在他们所处的位置上, 多了几分无可替代的真实,

  释迦的出现, 是在这部电影里给我的第一个震撼, 他沉默寡言, 唯一能做的事就是骑单车到处走走, 按理说这部电影里他完全是一个可有可无的角色, 他的出现并没有影响电影的进程, 他也并没有与其他人产生过多的交集, 他在影片中就只有一句台词, 既然如此, 难道他的出现就没有什么意义吗? 不是, 正相反, 他的存在, 恰恰是这部影片的核心之所在. 我们逐步来看, 这部电影讲的只是一个平凡的故事, 这个故事每个人看起来都有个独自的结局, 但即使如此, 这个电影的结局却永远不可以被改变. 因为这部电影的内涵决定这并不只是一个简单的故事, 它真正想表达的是像肚财, 菜铺, 释迦一样的底层人的一生, 而最重要的是他们的一生在故事的一开始就已经定格了的. 再具体说说释迦, 他在这部电影中相对于肚财和菜铺来说年纪相对较小, 但这种年纪上的小并没有在电影中具体表现出来, 相反导演正是利用了他表面上这个希微的身份, 自然地表现除了出了一种真真正正的佛的修行与畅然, 释迦贫穷, 但却整齐干净, 他虽然喜欢游荡, 但却只有肚财这一个朋友, 肚财虽然对他不好, 但肚财有困难的时候他却总是一直陪在肚财身边, 有人会说, 释迦有些傻, 的确, 他在有些事情上没有其他人那种尖锐的感情. 但这却正是他与众不同的地方--他没有私欲, 而释迦的名字也更加彰显了这种与众不同, 一种佛的象征, 照应了一种修行, 同时也是一种无为的理念. 反而, 当看到片中角色表面上看似都在"诚心向佛", 心里却没人真正在意佛究竟为何物, 尤其是当众人口口声声在念阿弥陀佛, 面露笑容, 实际上但却为了一件事情吵得不可开交, 句句诛心, 实属讽刺. 但释迦却完全不同, 片中说过没有人知道他的过去, 他是突然出现的. 也正是如此, 他给了人一种真正的佛的所在.

  //  大改, 看法极不客观
  最后想说一下, 这部电影在大陆是没有上映, 对於很多人来说这是十分遗憾的, 无法上映的因素有很多, 包括有一些关于性的片段掺杂其中, 而且还有一些关于政党和黑暗面的理解, 但我想其中最主要的原因还是因为题材的缘故, 这种题材的作品想要引入大陆必然要经过"相当严格"的审核, 但这种严格却针对的不是作品的艺术性, 而是一种无害性. 但这种所谓的无害性却恰恰相反害了中国的艺术作品, 而且也害了中国观众的审美, 让他们以为中国只能够产生出那类不伦不类的作品, 这种信心的丧失也反过来让艺术的创作者以为创作有意义, 有价值的作品是不会被认可的, 也就不在去努力了.　+一部含有相当多讽刺意味的台湾片想要在大陆上映基本是十分困难的, 而这些片段对于电影主题的理解是起到关键性作用的, 所以才有了无法上映的事实, 这里我想骂一句, 为什么荣获如此大奖的电影, 受到了这么多专业人士的肯定, 還迟迟无法与观众见面, 既然受到了如此多的褒奖, 想必电影是十分优秀的, 这个事实一定是毋庸置疑的, 难道就因为里面掺杂了一些性片段, 就可以妄自否定这部电影本身的价值吗, 如此之举, 是不是颇有些儿戏的. 我想说, 有些事情还是应该从自身多找些原因的, 既然国外可以有电影分级制度, 为什么我们不可以有, 既然你们大肆宣传国内电影市场多么辉煌, 每年又上升了多少个百分点, 是全世界票房的第几第几, 在这些数字背后, 在顾及国家领导的面子背后, 能不能真正实打实地想一想中国电影未来的道路发展, 想一想中国观众真正的电影感受, 在电影票连续下降的时候, 中国电影的质量是否也在下降, 难道作为一种文化消费的方式, 电影本身已经与文化一词渐行渐远, 还是那些上层的领导把我们当了傻子, 以为我们只喜欢看那些打打杀杀的过场戏, 五彩斑斓的特效和夸张的电脑剪辑, 不过我不认为如此, 我相信大多数人是真正喜欢并且希望看到中国电影一定会有自己独特的内涵和思考, 只不过是我们希望那一天早些到来.+

  这部影片不提生死, 或者说是把生死看作是一件极为平淡的事情   --- 与<<我不是药神>>区别

"关于彩蛋"
1. 故事的结局为开放式: 可以是发生天灾, 可以是启文东窗事发潜逃海外公司倒闭, 更可以是, 菜铺事後日复一日到工厂警卫室上班, 但在他的眼中, 公司其实已成为画面中的面貌.
2. "肚财, 菜铺, 释迦是同一个人"
